name: speed

channels:
  - pytorch
  - conda-forge

dependencies:
  - python=3.10
  - poetry
  - satpy
  - notebook
  - cryptography
  - numpy
  - cdsapi
  - requests
  - xarray
  - pyproj
  - appdirs
  - boto3
  - paramiko
  - shapely
  - sphinx_rtd_theme
  - pytest
  - appdirs
  - scipy
  - beautifulsoup4
  - lxml
  - netcdf4
  - matplotlib
  - cartopy
  - seaborn
  - cmocean
  - hdf4
  - hdf5
  - pyhdf
  - h5py
  - cfgrib
  - pip
  - pip:
    - git+https://github.com/see-geo/pansat@refactoring
    - jupyterlab-vim
    - bottleneck
